networks:
  scylla-migrator-spark-network:
    driver: bridge

services:
  spark-master:
    build: dockerfiles/spark
    command: master
    environment:
      SPARK_PUBLIC_DNS: localhost
      SPARK_HISTORY_OPTS: "-Dspark.history.ui.bindAddress=0.0.0.0 -Dspark.history.fs.logDirectory=file:/tmp/spark-events"
    ports:
      - 4040:4040
      - 8080:8080
      - 18080:18080  # Spark History Server
    volumes:
      - ./data/spark-master:/tmp/data
      - ./data/spark-events:/tmp/spark-events
      - ./migrator/target/scala-2.13:/jars
      - ./parquet-data:/parquet-data
      - ./:/app
      - ./web-app/log4j2-debug.properties:/spark/conf/log4j2-debug.properties
    networks:
      - scylla-migrator-spark-network

  spark-worker:
    build: dockerfiles/spark
    command: worker
    environment:
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 4G
      SPARK_WORKER_WEBUI_PORT: 8081
      SPARK_PUBLIC_DNS: localhost
    ports:
      - 8081:8081
    volumes:
      - ./data/spark-worker:/tmp/data
      - ./parquet-data:/parquet-data
      - ./web-app/log4j2-debug.properties:/spark/conf/log4j2-debug.properties
    depends_on:
      - spark-master
    networks:
      - scylla-migrator-spark-network

  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-local
    command: "-jar DynamoDBLocal.jar -sharedDb -inMemory"
    working_dir: /home/dynamodblocal
    ports:
      - "8001:8000"
    networks:
      - scylla-migrator-spark-network

  scylla-node1:
    image: scylladb/scylla:latest
    container_name: scylla-node1
    restart: always
    command: 
      - --seeds=scylla-node1
      - --alternator-port=8000
      - --alternator-write-isolation=always
      - --overprovisioned=1
      - --smp=1
    ports:
      - "8000:8000"  # Alternator Port
      - "9042:9042"  # CQL Port
    networks:
      - scylla-migrator-spark-network

  scylla-node2:
    image: scylladb/scylla:latest
    container_name: scylla-node2
    restart: always
    command: 
      - --seeds=scylla-node1
      - --alternator-port=8000
      - --alternator-write-isolation=always
      - --overprovisioned=1
      - --smp=1
    depends_on:
      - scylla-node1
    networks:
      - scylla-migrator-spark-network

  scylla-node3:
    image: scylladb/scylla:latest
    container_name: scylla-node3
    restart: always
    command: 
      - --seeds=scylla-node1
      - --alternator-port=8000
      - --alternator-write-isolation=always
      - --overprovisioned=1
      - --smp=1
    depends_on:
      - scylla-node1
    networks:
      - scylla-migrator-spark-network

  web-app:
    build: web-app
    working_dir: /app/web-app
    ports:
      - "5000:5000"
    environment:
      SPARK_MASTER_HOST: spark-master
      MIGRATOR_CONFIG_PATH: /app/config.yaml
      USE_DOCKER_EXEC: "1"
      FLASK_APP: app.py
    volumes:
      - ./:/app
      - ./migrator/target/scala-2.13:/jars
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - spark-master
    networks:
      - scylla-migrator-spark-network
